on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftpupload.net
        FTP_USERNAME: epiz_25055110
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: htdocs
        ARGS: --exclude-glob=.git*/** --exclude-glob=.git** --exclude-glob=.yaml**
     
        # --delete arg will delete files on the server if you've deleted them in git
